INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('Serres', 41.092083, 23.541016, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('Provatas', 41.068238, 23.390686, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('A. Kamila',  	41.058320, 23.424134, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('K. Kamila', 41.020431, 23.483293, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('K. Mitrousi', 41.058680, 23.457547, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('Koumaria', 41.016434, 23.434656, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('Skoutari', 41.020032, 23.520701, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('Adelfiko', 41.014645, 23.457354, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('Ag. Eleni', 41.003545, 23.559196, FALSE);
INSERT INTO VILLAGE (name, latitude, longitude, visited) VALUES ('Peponia', 40.988154, 23.516756, FALSE);


INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (1, 2, 15.1);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (1, 5, 9.4);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (1, 7, 9.1);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (2, 1, 15.1);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (2, 3, 12.4);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (3, 2, 12.4);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (3, 5, 3.1);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (3, 6, 6.3);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (4, 5, 7);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (4, 6, 5.7);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (4, 7, 3.2);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (5, 1, 9.4);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (5, 3, 3.1);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (5, 4, 7);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (5, 6, 5.5);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (6, 3, 6.3);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (6, 4, 5.7);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (6, 5, 5.5);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (6, 8, 2.5);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (7, 1, 9.1);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (7, 4, 3.2);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (7, 9, 4.6);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (7, 10, 4.5);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (8, 6, 2.5);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (8, 10, 6.8);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (9, 7, 4.6);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (9, 10, 4.7);

INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (10, 7, 4.5);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (10, 8, 6.8);
INSERT INTO PATH (ORIGIN_ID, DESTINATION_ID, distance) VALUES (10, 9, 4.7);
